# Generated by Django 3.0.2 on 2020-01-29 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InfoTCU',
            fields=[
                ('Profesor', models.CharField(max_length=30)),
                ('Nombre', models.CharField(max_length=30)),
                ('Codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Telefono', models.CharField(max_length=8)),
                ('Correo', models.EmailField(max_length=30)),
                ('Descripcion', models.CharField(max_length=500)),
                ('Facebook', models.CharField(max_length=100)),
                ('Youtube', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=30)),
                ('Estado', models.CharField(max_length=30)),
                ('Descripcion', models.CharField(max_length=500)),
                ('Visble', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('Nombre', models.CharField(max_length=30)),
                ('Primer_Apellido', models.CharField(max_length=30)),
                ('Segundo_Apellido', models.CharField(max_length=30)),
                ('Identificacion', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('Carrera', models.CharField(max_length=30)),
                ('Correo', models.EmailField(max_length=30)),
                ('Telefono', models.CharField(max_length=8)),
                ('Estado', models.CharField(max_length=30)),
                ('Horas', models.IntegerField(max_length=3)),
                ('Proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=30)),
                ('Fecha', models.DateField(auto_now=True)),
                ('Tipo', models.CharField(choices=[('RP', 'REPORTE'), ('ST', 'ESTUDIO'), ('ED', 'ESTADISTICA')], max_length=2)),
                ('Lugar', models.CharField(max_length=30)),
                ('Enlace', models.CharField(max_length=100)),
                ('Proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Proyecto')),
            ],
        ),
    ]
