# Generated by Django 3.0.2 on 2020-01-30 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20200130_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='Horas',
            field=models.IntegerField(),
        ),
    ]
