# Generated by Django 3.0.2 on 2020-02-04 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20200130_0953'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticias',
            fields=[
                ('Descripcion', models.CharField(max_length=1000)),
                ('Titulo', models.CharField(max_length=100)),
                ('Imagen', models.CharField(max_length=200)),
                ('Identificacion', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
    ]
