# Generated by Django 3.0.2 on 2020-02-04 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_noticias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tcudato',
            name='Nombre',
            field=models.CharField(max_length=100),
        ),
    ]
