# Generated by Django 3.0.2 on 2020-02-06 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20200204_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='Imagen',
            field=models.ImageField(upload_to='images'),
        ),
    ]
