# Generated by Django 3.0.2 on 2020-02-17 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20200206_1441'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proyecto',
            old_name='Visble',
            new_name='Visible',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='Imagen',
            field=models.ImageField(null=True, upload_to='polls/images'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='Enlace',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='documento',
            name='Lugar',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='documento',
            name='Nombre',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='Carrera',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='Correo',
            field=models.EmailField(max_length=70),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='Nombre',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='Primer_Apellido',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='Segundo_Apellido',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='Imagen',
            field=models.ImageField(upload_to='polls/images'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='Descripcion',
            field=models.CharField(max_length=700),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='Estado',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='Nombre',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='tcudato',
            name='Codigo',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tcudato',
            name='Correo',
            field=models.EmailField(max_length=70),
        ),
        migrations.AlterField(
            model_name='tcudato',
            name='Facebook',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='tcudato',
            name='Profesor',
            field=models.CharField(max_length=210),
        ),
        migrations.AlterField(
            model_name='tcudato',
            name='Youtube',
            field=models.CharField(max_length=200),
        ),
    ]
