# Generated by Django 3.0.2 on 2020-02-17 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20200217_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='Imagen',
            field=models.ImageField(upload_to='polls/images'),
        ),
    ]
