# Generated by Django 3.0.2 on 2020-02-20 14:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_auto_20200217_0914'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pasantia',
            fields=[
                ('Profesor', models.CharField(max_length=210)),
                ('Nombre', models.CharField(max_length=100)),
                ('Codigo', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='Horas',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='Matricula',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proyecto',
            name='Inicio',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='documento',
            name='Fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='documento',
            name='Tipo',
            field=models.CharField(choices=[('PL', 'PLAN DE EMERGENCIA'), ('ET', 'ESTUDIO'), ('OT', 'OTROS')], max_length=2),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='Estado',
            field=models.CharField(choices=[('FN', 'FINALIZADO'), ('EC', 'EN CURSO')], max_length=2),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='Pasantia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Pasantia'),
        ),
    ]
